### ISSUE TITLE
Option for Email Template Customization  

### ISSUE THREAD

**Issue by code-vj** [LoginRadius/ps-softlist#4]
The email template is static and content is basic. it would be better for adding an option for the email template and content Customization

**Comment by nuwan94** [comment]
Hi @code-vj, 

I have a few questions about the **customization**?

- Does these options needed to be provided **interactively on runtime**?
OR
-  Something like showing the **numbers/stats in the email body** is enough? 

Either, I would like to work on this issue.  😃
Can you assign me to this issue, please?

**Comment by code-vj** [comment]
Hi @nuwan94  , 

Users can choose or pass the email template runtime. The script will use some place holders so need to create an email template with placeholders, actual values will replace by script
